version: "2"
services:
  app:
    image: golang:1.15
    ports:
      - "5555:5555"
    volumes:
      - .:/abgenius
    working_dir: /abgenius
    command: bash -c "go build . && ./abgenius"
    links:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo
    restart: unless-stopped
  mongo:
    image: mongo
    volumes:
      - ./mdata:/data/db
    restart: unless-stopped
volumes:
  mdata: