version: "2"
services:
  app:
    image: golang:1.9.2
    ports:
      - "5555:5555"
    volumes:
      - .:/go/src/abgenius
    working_dir: /go/src/abgenius
    command: bash -c "go get github.com/golang/dep/cmd/dep && dep ensure && go build . && ./abgenius"
    #command: bash -c "go build . && ./abgenius"
    links:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo
    restart: unless-stopped
  mongo:
    image: mongo
    volumes:
      - ./mdata:/data/db
    restart: unless-stopped
volumes:
  mdata: