//This file contains legacy code to store the default V/Q values for the 20 alveoli in the model

const NORM_QPERCENT: number[] = [];
const NORM_VPERCENT: number[] = [];

const EMPH_QPERCENT: number[] = [];
const EMPH_VPERCENT: number[] = [];

const COPD_QPERCENT: number[] = [];
const COPD_VPERCENT: number[] = [];

const BRON_QPERCENT: number[] = [];
const BRON_VPERCENT: number[] = [];

// Renumbered Normal, Emphysema and COPD models, odd # compartments
// reordered as 1-10 and even # compartment as 11-20

// Normal Lung Compartment Percentages
NORM_QPERCENT[1] = 1.4;
NORM_QPERCENT[11] = 2;
NORM_QPERCENT[2] = 2;
NORM_QPERCENT[12] = 3;
NORM_QPERCENT[3] = 3;
NORM_QPERCENT[13] = 4.2;
NORM_QPERCENT[4] = 4.2;
NORM_QPERCENT[14] = 4.8;
NORM_QPERCENT[5] = 4.8;
NORM_QPERCENT[15] = 5.2;
NORM_QPERCENT[6] = 5.2;
NORM_QPERCENT[16] = 5.5;
NORM_QPERCENT[7] = 5.5;
NORM_QPERCENT[17] = 6.5;
NORM_QPERCENT[8] = 6.5;
NORM_QPERCENT[18] = 7;
NORM_QPERCENT[9] = 7;
NORM_QPERCENT[19] = 7.4;
NORM_QPERCENT[10] = 7.4;
NORM_QPERCENT[20] = 7.4;

NORM_VPERCENT[1] = 5;
NORM_VPERCENT[11] = 5;
NORM_VPERCENT[2] = 5;
NORM_VPERCENT[12] = 5;
NORM_VPERCENT[3] = 5;
NORM_VPERCENT[13] = 5;
NORM_VPERCENT[4] = 5;
NORM_VPERCENT[14] = 5;
NORM_VPERCENT[5] = 5;
NORM_VPERCENT[15] = 5;
NORM_VPERCENT[6] = 5;
NORM_VPERCENT[16] = 5;
NORM_VPERCENT[7] = 5;
NORM_VPERCENT[17] = 5;
NORM_VPERCENT[8] = 5;
NORM_VPERCENT[18] = 5;
NORM_VPERCENT[9] = 5;
NORM_VPERCENT[19] = 5;
NORM_VPERCENT[10] = 5;
NORM_VPERCENT[20] = 5;

// Emphysema compartments
EMPH_QPERCENT[1] = 0.5;
EMPH_QPERCENT[11] = 1;
EMPH_QPERCENT[2] = 1;
EMPH_QPERCENT[12] = 1;
EMPH_QPERCENT[3] = 1;
EMPH_QPERCENT[13] = 1;
EMPH_QPERCENT[4] = 1;
EMPH_QPERCENT[14] = 1;
EMPH_QPERCENT[5] = 1;
EMPH_QPERCENT[15] = 1;
EMPH_QPERCENT[6] = 3;
EMPH_QPERCENT[16] = 2;
EMPH_QPERCENT[7] = 5.5;
EMPH_QPERCENT[17] = 8.5;
EMPH_QPERCENT[8] = 11.5;
EMPH_QPERCENT[18] = 14.5;
EMPH_QPERCENT[9] = 14.5;
EMPH_QPERCENT[19] = 15.5;
EMPH_QPERCENT[10] = 12.5;
EMPH_QPERCENT[20] = 3;

EMPH_VPERCENT[1] = 6;
EMPH_VPERCENT[11] = 7;
EMPH_VPERCENT[2] = 7;
EMPH_VPERCENT[12] = 6;
EMPH_VPERCENT[3] = 6;
EMPH_VPERCENT[13] = 6;
EMPH_VPERCENT[4] = 5;
EMPH_VPERCENT[14] = 5;
EMPH_VPERCENT[5] = 4;
EMPH_VPERCENT[15] = 3;
EMPH_VPERCENT[6] = 3.5;
EMPH_VPERCENT[16] = 2;
EMPH_VPERCENT[7] = 5;
EMPH_VPERCENT[17] = 6;
EMPH_VPERCENT[8] = 7;
EMPH_VPERCENT[18] = 7;
EMPH_VPERCENT[9] = 6;
EMPH_VPERCENT[19] = 4.5;
EMPH_VPERCENT[10] = 4;
EMPH_VPERCENT[20] = 0;

// COPD compartments
COPD_QPERCENT[1] = 0.1;
COPD_QPERCENT[11] = 0.1;
COPD_QPERCENT[2] = 0.1;
COPD_QPERCENT[12] = 0.1;
COPD_QPERCENT[3] = 0.1;
COPD_QPERCENT[13] = 3;
COPD_QPERCENT[4] = 8;
COPD_QPERCENT[14] = 9;
COPD_QPERCENT[5] = 9;
COPD_QPERCENT[15] = 10;
COPD_QPERCENT[6] = 7;
COPD_QPERCENT[16] = 7;
COPD_QPERCENT[7] = 6;
COPD_QPERCENT[17] = 5;
COPD_QPERCENT[8] = 5;
COPD_QPERCENT[18] = 5.5;
COPD_QPERCENT[9] = 6.2;
COPD_QPERCENT[19] = 8;
COPD_QPERCENT[10] = 5.4;
COPD_QPERCENT[20] = 5.4;

COPD_VPERCENT[1] = 8;
COPD_VPERCENT[11] = 8;
COPD_VPERCENT[2] = 8;
COPD_VPERCENT[12] = 8;
COPD_VPERCENT[3] = 8;
COPD_VPERCENT[13] = 5;
COPD_VPERCENT[4] = 6;
COPD_VPERCENT[14] = 9;
COPD_VPERCENT[5] = 9;
COPD_VPERCENT[15] = 8;
COPD_VPERCENT[6] = 7;
COPD_VPERCENT[16] = 6;
COPD_VPERCENT[7] = 5;
COPD_VPERCENT[17] = 1;
COPD_VPERCENT[8] = 1;
COPD_VPERCENT[18] = 1;
COPD_VPERCENT[9] = 1;
COPD_VPERCENT[19] = 1;
COPD_VPERCENT[10] = 0;
COPD_VPERCENT[20] = 0;

// Bronchial Obstruction compartments
BRON_QPERCENT[1] = 1.4;
BRON_QPERCENT[11] = 2;
BRON_QPERCENT[2] = 2.2;
BRON_QPERCENT[12] = 4;
BRON_QPERCENT[3] = 4;
BRON_QPERCENT[13] = 4.5;
BRON_QPERCENT[4] = 4.5;
BRON_QPERCENT[14] = 4.8;
BRON_QPERCENT[5] = 4.8;
BRON_QPERCENT[15] = 5.2;
BRON_QPERCENT[6] = 5.2;
BRON_QPERCENT[16] = 5.5;
BRON_QPERCENT[7] = 5.5;
BRON_QPERCENT[8] = 6.5;
BRON_QPERCENT[9] = 6.5;
BRON_QPERCENT[10] = 7.0;
BRON_QPERCENT[17] = 6.2;
BRON_QPERCENT[18] = 6.2;
BRON_QPERCENT[19] = 6.5;
BRON_QPERCENT[20] = 7.5;

BRON_VPERCENT[1] = 6;
BRON_VPERCENT[11] = 6;
BRON_VPERCENT[2] = 6.5;
BRON_VPERCENT[12] = 6.5;
BRON_VPERCENT[3] = 6;
BRON_VPERCENT[13] = 6;
BRON_VPERCENT[4] = 6;
BRON_VPERCENT[14] = 6.5;
BRON_VPERCENT[5] = 6.5;
BRON_VPERCENT[15] = 6.5;
BRON_VPERCENT[6] = 6.5;
BRON_VPERCENT[16] = 7;
BRON_VPERCENT[7] = 7;
BRON_VPERCENT[8] = 6.5;
BRON_VPERCENT[9] = 5.5;
BRON_VPERCENT[10] = 5;
BRON_VPERCENT[17] = 0;
BRON_VPERCENT[18] = 0;
BRON_VPERCENT[19] = 0;
BRON_VPERCENT[20] = 0;

export interface VQPreset {
	name: string;
	vqZones: [number, number][];
	tvDeadspacePct: number;
}

const zip = <T>(arr1: T[], arr2: T[]): [T, T][] => arr1.map((k, i) => [k, arr2[i]]);

export const vqPresets: VQPreset[] = [
	{
		name: "Normal",
		vqZones: zip(NORM_VPERCENT, NORM_QPERCENT),
		tvDeadspacePct: 5,
	},
	{
		name: "Emphysema",
		vqZones: zip(EMPH_VPERCENT, EMPH_QPERCENT),
		tvDeadspacePct: 20,
	},
	{
		name: "Chronic Bronchitis",
		vqZones: zip(COPD_VPERCENT, COPD_QPERCENT),
		tvDeadspacePct: 10,
	},
	{
		name: "Bronchial Obstruction",
		vqZones: zip(BRON_VPERCENT, BRON_QPERCENT),
		tvDeadspacePct: 5,
	},
];
